config:
  batch_size: 32
  lr: 2.0e-05
  model_name: bert-base-uncased
  nepochs: 10
  save_path: models/big
  test_data_path: data/all_combined/all_arguments_test.csv
  tokenizer_name: bert-base-uncased
  train_data_path: data/all_combined/all_arguments_train.csv
  use_hypothesis: false
  use_sa: true
  val_data_path: data/all_combined/all_arguments_val.csv
  val_freq: 1
