nepochs: 10
val_freq: 1
lr: 0.00002
save_path: "/cluster/scratch/gboeshertz/models/combined_electra_hypo"
test_save_path: "models/combined_electra_hypo/epoch2.ckpt"
model_name : "google/electra-base-discriminator"
tokenizer_name: "google/electra-base-discriminator"
batch_size: 32
train_data_path: "data/all_combined/all_arguments_train.csv"
val_data_path: "data/all_combined/all_arguments_val.csv"
test_data_path: "data/all_combined/all_arguments_test.csv"
use_sa: False
use_hypothesis: True
test_out_path : "combined_electra_hypo"
