nepochs: 10
val_freq: 1
lr: 0.00002
save_path: "/cluster/scratch/gboeshertz/models/combined_twitrob_hypo"
test_save_path: "/cluster/scratch/gboeshertz/models/twitrob_hypo/model.ckpt"
model_name : "cardiffnlp/twitter-roberta-base-sentiment-latest"
tokenizer_name: "cardiffnlp/twitter-roberta-base-sentiment-latest"
batch_size: 32
train_data_path: "data/all_combined/all_arguments_train.csv"
val_data_path: "data/all_combined/all_arguments_val.csv"
test_data_path: "data/all_combined/all_arguments_test.csv"
use_sa: False
use_hypothesis: True
test_out_path : "combined_twitrob_hypo"
