nepochs: 1
val_freq: 1
lr: 0.00002
save_path: "models/combined"
test_save_path: "models/combined"

model_name : "bert-base-uncased"
tokenizer_name: "bert-base-uncased"
batch_size: 32
train_data_path: "data/all_combined/all_arguments_train.csv"
val_data_path: "data/all_combined/all_arguments_val.csv"
test_data_path: "data/all_combined/all_arguments_test.csv"
use_sa: False
use_hypothesis: False
test_out_path : "combined"
