nepochs: 10
val_freq: 1
lr: 0.00002
save_path: "/cluster/scratch/gboeshertz/models/combined_hypo"
test_save_path: "models/combined_sa_hypo/epoch=3-step=1036.ckpt"
model_name : "bert-base-uncased"
tokenizer_name: "bert-base-uncased"
batch_size: 32
train_data_path: "data/all_combined/all_arguments_train.csv"
val_data_path: "data/all_combined/all_arguments_val.csv"
test_data_path: "data/all_combined/all_arguments_test.csv"
use_sa: False
use_hypothesis: True
test_out_path : "combined_hypo"
