nepochs: 10
val_freq: 1
lr: 0.00002
save_path: "/cluster/scratch/gboeshertz/models/climate_test_hypo_twitrob"
test_save_path: "models/climate_test_hypo_twitrob"
model_name : "cardiffnlp/twitter-roberta-base-sentiment-latest"
tokenizer_name: "cardiffnlp/twitter-roberta-base-sentiment-latest"
batch_size: 32
train_data_path: "data/climate_test/non_climate_train.csv"
val_data_path: "data/climate_test/non_climate_val.csv"
test_data_path: "data/climate_test/climate_test.csv"
use_sa: False
use_hypothesis: True
test_out_path : "climate_test_hypo_twitrob"
