nepochs: 10
val_freq: 1
lr: 0.00002
save_path: "/cluster/scratch/gboeshertz/models/paper_fallacies_climate_test"
test_save_path: "models/paper_fallacies_climate_test"

model_name : "bert-base-uncased"
tokenizer_name: "bert-base-uncased"
batch_size: 32
train_data_path: "data/paper_fallacies_climate_test/non_climate_train.csv"
val_data_path: "data/paper_fallacies_climate_test/non_climate_val.csv"
test_data_path: "data/paper_fallacies_climate_test/climate_test.csv"
use_sa: False
use_hypothesis: True
test_out_path : "paper_fallacies_climate_test"
