nepochs: 10
val_freq: 1
lr: 0.00002
save_path: "models/big"
model_name : "bert-base-uncased"
tokenizer_name: "bert-base-uncased"
batch_size: 32
train_data_path: "data/essay/paper_and_non_fallacies_train.csv"
val_data_path: "data/essay/paper_and_non_fallacies_val.csv"
test_data_path: "data/essay/paper_and_non_fallacies_test.csv"
use_sa: True
use_hypothesis: False